//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFKalendarz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalendarz
    {
        public int Id { get; set; }
        public string Monday { get; set; }

        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
    

   
        public class coord
        {
            double lon { get; set; }
            double lat { get; set; }
        }
        public class weather
        {
            string main { get; set; }
            string description {  get; set; }
            string icion { get; set; }
        }
        public class main
        {
            public double temp { get; set; }
            double pressure { get; set; }
            double humidity { get; set; }
        }

        public class wind
        {
            double speed { get; set; }
        }
        public class sys
        {
            long sunrise { get; set; }
            long sunset { get; set; }
        }
        public class root
        {
            public coord coord { get; set; }
            public List <weather> weather { get; set; }
            public main main { get; set; }
            public wind wind { get; set; }
            public sys sys { get; set; }

        }
    }
}
